//index.js
//获取应用实例
const app = getApp()

Page({
  options: {
    addGlobalClass: true,
  },
  data: {
    DotStyle: true,
    swiperList: [{
      id: 0,
      type: 'image',
      url: 'https://ossweb-img.qq.com/images/lol/web201310/skin/big84000.jpg'
    }, {
      id: 1,
      type: 'image',
      url: 'https://ossweb-img.qq.com/images/lol/web201310/skin/big84001.jpg',
    }, {
      id: 2,
      type: 'image',
      url: 'https://ossweb-img.qq.com/images/lol/web201310/skin/big39000.jpg'
    }, {
      id: 3,
      type: 'image',
      url: 'https://ossweb-img.qq.com/images/lol/web201310/skin/big10001.jpg'
    }, {
      id: 4,
      type: 'image',
      url: 'https://ossweb-img.qq.com/images/lol/web201310/skin/big25011.jpg'
    }, {
      id: 5,
      type: 'image',
      url: 'https://ossweb-img.qq.com/images/lol/web201310/skin/big21016.jpg'
    }, {
      id: 6,
      type: 'image',
      url: 'https://ossweb-img.qq.com/images/lol/web201310/skin/big99008.jpg'
    }],
    TabCur: 0,
    scrollLeft: 0,
    navList: [{
        name: "热门",
        elements: [{
            title: '一寸',
            name: 'px : 295 x 413',
            color: 'purple',
            icon: 'mm : 25 x 35',
            px:'295,413',
          },
          {
            title: '二寸 ',
            name: 'px : 413 x 579',
            color: 'mauve',
            icon: 'mm : 35 x 49',
            px:'413,579',
          },
          {
            title: '驾照',
            name: 'px : 259 x 377',
            color: 'pink',
            icon: 'mm : 22 x 32',
            px:'259,377',
          },
          {
            title: '简历照片',
            name: 'px : 295 x 413',
            color: 'brown',
            icon: 'mm : 25 x 35',
            px:'295,413',
          },
          {
            title: '小二寸',
            name: 'px : 413 x 531',
            color: 'red',
            icon: 'mm : 35 x 45',
            px:'413,531',
          },
          {
            title: '结婚证',
            name: 'px : 413 x 579',
            color: 'orange',
            icon: 'mm : 35 x 49',
            px:'413,579',
          },
          {
            title: '大一寸',
            name: 'px :390 x 567',
            color: 'green',
            icon: 'mm : 33 x 48',
            px:'390,567',
          },
          {
            title: '社保卡',
            name: 'px : 358 x 441',
            color: 'olive',
            icon: 'mm : 26 x 32',
            px:'358,441',
          },
          {
            title: '小一寸',
            name: 'px : 260 x 378',
            color: 'grey',
            icon: 'mm : 22 x 32',
            px:'260,378',
          },
          {
            title: '五寸',
            name: 'px : 1051 x 1500',
            color: 'cyan',
            icon: 'mm : 89 x 127',
            px:'1051,1500',
          },
          {
            title: '四寸',
            name: 'px : 897 x 1204',
            color: 'cyan',
            icon: 'mm : 76 x 102',
            px:'897,1204',
          },
        ],
      },
      {
        name: "常规",
        elements: [{
            title: '一寸',
            name: 'px : 295 x 413',
            color: 'purple',
            icon: 'mm : 25 x 35',
            px:'295,413',
          },
          {
            title: '小一寸',
            name: 'px : 260 x 378',
            color: 'grey',
            icon: 'mm : 22 x 32',
            px:'260,378',
          },
          {
            title: '大一寸',
            name: 'px :390 x 567',
            color: 'green',
            icon: 'mm : 33 x 48',
            px:'390,567',
          },
          {
            title: '二寸 ',
            name: 'px : 413 x 579',
            color: 'mauve',
            icon: 'mm : 35 x 49',
            px:'413,579',
          },
          {
            title: '小二寸',
            name: 'px : 413 x 531',
            color: 'red',
            icon: 'mm : 35 x 45',
            px:'413,531',
          },
          {
            title: '大二寸',
            name: 'px : 413 x 625',
            color: 'red',
            icon: 'mm : 35 x 53',
            px:'413,625',
          },
          {
            title: '三寸',
            name: 'px : 637 x 992',
            color: 'cyan',
            icon: 'mm : 54 x 84',
            px:'637,992',
          },
          {
            title: '四寸',
            name: 'px : 897 x 1204',
            color: 'cyan',
            icon: 'mm : 76 x 102',
            px:'897,1204',
          },
          {
            title: '五寸',
            name: 'px : 1051 x 1500',
            color: 'cyan',
            icon: 'mm : 89 x 127',
            px:'1051,1500',
          },
          
        ],
      },
      {
        name: "护照",
        elements: [{
            title: '美国签证',
            name: 'px : 602 x 602',
            color: 'purple',
            icon: 'mm : 51 x 51',
            px:'602,602',
          },
          {
            title: '日本签证',
            name: 'px : 531 x 531',
            color: 'grey',
            icon: 'mm : 45 x 45',
            px:'531,531',
          },
          {
            title: '越南签证',
            name: 'px : 472 x 708',
            color: 'green',
            icon: 'mm : 40 x 60',
            px:'472,708',
          },
          {
            title: '入台签证 ',
            name: 'px : 413 x 531',
            color: 'mauve',
            icon: 'mm : 35 x 45',
            px:'413,531',
          },
          {
            title: '电子护照',
            name: 'px : 389 x 566',
            color: 'red',
            icon: 'mm : 33 x 48',
            px:'389,566',
          },
          {
            title: '海外申请护照在线预约',
            name: 'px : 389 x 566',
            color: 'red',
            icon: 'mm : 33 x 48',
            px:'389,566',
          },
          {
            title: '冰岛签证',
            name: 'px : 472 x 590',
            color: 'cyan',
            icon: 'mm : 40 x 50',
            px:'472,590',
          },
          {
            title: '世界通用签证',
            name: 'px : 413 x 531',
            color: 'cyan',
            icon: 'mm : 35 x 45',
            px:'413,531',
          },
          {
            title: '港澳通行证',
            name: 'px : 389 x 566',
            color: 'cyan',
            icon: 'mm : 33 x 48',
            px:'389,566',
          },
          {
            title: '韩国签证',
            name: 'px : 413 x 531',
            color: 'cyan',
            icon: 'mm : 35 x 45',
            px:'413,531',
          },
          {
            title: '泰国签证',
            name: 'px : 413 x 531',
            color: 'cyan',
            icon: 'mm : 35 x 45',
            px:'413,531',
          },
          {
            title: '印度签证',
            name: 'px : 602 x 602',
            color: 'cyan',
            icon: 'mm : 51 x 51',
            px:'602,602',
          },
          {
            title: '以色列签证',
            name: 'px : 602 x 602',
            color: 'cyan',
            icon: 'mm : 51 x 51',
            px:'602,602',
          },
          {
            title: '签证采集',
            name: 'px : 354 x 472',
            color: 'cyan',
            icon: 'mm : 30 x 40',
            px:'354,472',
          },
          {
            title: '马来西亚签证',
            name: 'px : 413 x 531',
            color: 'cyan',
            icon: 'mm : 35 x 45',
            px:'413,531',
          },
          {
            title: '新西兰签证',
            name: 'px : 897 x 1204',
            color: 'cyan',
            icon: 'mm : 76 x 102',
            px:'897,1204',
          },
          {
            title: '意大利签证',
            name: 'px : 413 x 472',
            color: 'cyan',
            icon: 'mm : 35 x 40',
            px:'413,472',
          },
          {
            title: '阿根廷签证',
            name: 'px : 472 x 472',
            color: 'cyan',
            icon: 'mm : 40 x 40',
            px:'472,472',
          },
          {
            title: '巴西签证',
            name: 'px : 472 x 590',
            color: 'cyan',
            icon: 'mm : 40 x 50',
            px:'472,590',
          },
          {
            title: '肯尼亚签证',
            name: 'px : 590 x 590',
            color: 'cyan',
            icon: 'mm : 50 x 50',
            px:'590,590',
          },
          {
            title: '入金证',
            name: 'px : 413 x 531',
            color: 'cyan',
            icon: 'mm : 35 x 45',
            px:'413,531',
          },
        ],
      },
      {
        name: "考试",
        elements: [{
            title: '导游证',
            name: 'px : 285 x 385',
            color: 'purple',
            icon: 'mm : 24 x 33',
            px:'285,385',
          },
          {
            title: '教师资格证',
            name: 'px : 295 x 413',
            color: 'grey',
            icon: 'mm : 25 x 35',
            px:'295,413',
          },
          {
            title: '入学照',
            name: 'px : 295 x 413',
            color: 'green',
            icon: 'mm : 25 x 35',
            px:'295,413',
          },
          {
            title: '国考 ',
            name: 'px : 413 x 531',
            color: 'mauve',
            icon: 'mm : 35 x 45',
            px:'413,531',
          },
          {
            title: '国家司法考试',
            name: 'px : 413 x 626',
            color: 'red',
            icon: 'mm : 35 x 53',
            px:'413,626',
          },
          {
            title: '二级建造师照片',
            name: 'px : 295 x 413',
            color: 'red',
            icon: 'mm : 25 x 35',
            px:'295,413',
          },
          {
            title: '一级建造师证',
            name: 'px : 472 x 630',
            color: 'cyan',
            icon: 'mm : 40 x 53',
            px:'472,630',
          },
          {
            title: '二级建造师证',
            name: 'px : 455 x 661',
            color: 'cyan',
            icon: 'mm : 39 x 56',
            px:'455,661',
          },
          {
            title: '职业兽医资格证',
            name: 'px : 230 x 334',
            color: 'cyan',
            icon: 'mm : 19 x 28',
            px:'230,334',
          },
          {
            title: '自考证件照',
            name: 'px : 384 x 512',
            color: 'cyan',
            icon: 'mm : 33 x 43',
            px:'384,512',
          },
          {
            title: '成人自考',
            name: 'px : 294 x 413',
            color: 'cyan',
            icon: 'mm : 25 x 35',
            px:'294,413',
          },
          {
            title: '会计从业资格证',
            name: 'px : 295 x 413',
            color: 'cyan',
            icon: 'mm : 25 x 35',
            px:'295,413',
          },
          {
            title: '英语四六级考试',
            name: 'px : 144 x 192',
            color: 'cyan',
            icon: 'mm : 33 x 48',
            px:'144,192',
          },
          {
            title: '学位英语',
            name: 'px : 390 x 567',
            color: 'cyan',
            icon: 'mm : 33 x 48',
            px:'390,567',
          },
          {
            title: '英语AB级考试',
            name: 'px : 390 x 567',
            color: 'cyan',
            icon: 'mm : 33 x 48',
            px:'390,567',
          },
          {
            title: '普通话水平测试',
            name: 'px : 390 x 567',
            color: 'cyan',
            icon: 'mm : 33 x 48',
            px:'390,567',
          },
          {
            title: '执业药师考试',
            name: 'px : 295 x 413',
            color: 'cyan',
            icon: 'mm : 25 x 35',
            px:'295,413',
          },
          {
            title: '执业药师资格考试',
            name: 'px : 413 x 579',
            color: 'cyan',
            icon: 'mm : 35 x 49',
            px:'413,579',
          },
          {
            title: '执业医师资格报名',
            name: 'px : 354 x 472',
            color: 'cyan',
            icon: 'mm : 30 x 40',
            px:'354,472',
          },
          {
            title: '学籍照片',
            name: 'px : 358 x 441',
            color: 'cyan',
            icon: 'mm : 30 x 37',
            px:'358,441',
          },
          {
            title: '入学报名',
            name: 'px : 295 x 413',
            color: 'cyan',
            icon: 'mm : 25 x 35',
            px:'295,413',
          },
          {
            title: '大学入学',
            name: 'px : 413 x 531',
            color: 'cyan',
            icon: 'mm : 35 x 45',
            px:'413,531',
          },
          {
            title: '高考报名',
            name: 'px : 420 x 560',
            color: 'cyan',
            icon: 'mm : 36 x 47',
            px:'420,560',
          },
          {
            title: '全国计算机考试',
            name: 'px : 571 x 800',
            color: 'cyan',
            icon: 'mm : 48 x 68',
            px:'571,800',
          },
          {
            title: '护士执业资格考试',
            name: 'px : 210 x 276',
            color: 'cyan',
            icon: 'mm : 18 x 23',
            px:'210,276',
          },
          {
            title: '成人自考本科',
            name: 'px : 480 x 720',
            color: 'cyan',
            icon: 'mm : 41 x 61',
            px:'480,720',
          },
          {
            title: '自考学位外语考试',
            name: 'px : 390 x 567',
            color: 'cyan',
            icon: 'mm : 33 x 48',
            px:'390,567',
          },
          {
            title: '英语三级考试',
            name: 'px : 144 x 192',
            color: 'cyan',
            icon: 'mm : 33 x 48',
            px:'144,192',
          },
          {
            title: '西藏二级建造师',
            name: 'px : 455 x 661',
            color: 'cyan',
            icon: 'mm : 39 x 56',
            px:'455,661',
          },
          {
            title: '国家公务员考试',
            name: 'px : 295 x 413',
            color: 'cyan',
            icon: 'mm : 25 x 35',
            px:'295,413',
          },
          {
            title: '保险职业认证',
            name: 'px : 210 x 270',
            color: 'cyan',
            icon: 'mm : 18 x 23',
            px:'210,270',
          },
          {
            title: '注册会计师',
            name: 'px : 178 x 220',
            color: 'cyan',
            icon: 'mm : 15 x 19',
            px:'178,220',
          },
          {
            title: '保险职业证',
            name: 'px : 210 x 370',
            color: 'cyan',
            icon: 'mm : 18 x 31',
            px:'210,370',
          },
          
        ],
      },
      {
        name: "其他",
        elements: [{
            title: '居住证',
            name: 'px : 307 x 377',
            color: 'purple',
            icon: 'mm : 26 x 32',
            px:'307,377',
          },
          {
            title: '社保卡',
            name: 'px : 358 x 441',
            color: 'grey',
            icon: 'mm : 26 x 32',
            px:'358,441',
          },
          {
            title: '驾照',
            name: 'px : 259 x 377',
            color: 'green',
            icon: 'mm : 22 x 32',
            px:'259,377',
          },
          {
            title: '简历照片 ',
            name: 'px : 295 x 413',
            color: 'mauve',
            icon: 'mm : 25 x 35',
            px:'295,413',
          },
          {
            title: '医保证',
            name: 'px : 358 x 441',
            color: 'red',
            icon: 'mm : 26 x 32',
            px:'358,441',
          },
          {
            title: '健康证',
            name: 'px : 295 x 413',
            color: 'red',
            icon: 'mm : 25 x 35',
            px:'295,413',
          },
          {
            title: '执法证',
            name: 'px : 265 x 351',
            color: 'cyan',
            icon: 'mm : 22 x 30',
            px:'265,351',
          },
          {
            title: '校园卡',
            name: 'px : 240 x 320',
            color: 'cyan',
            icon: 'mm : 20 x 27',
            px:'240,320',
          },
          {
            title: '结婚证',
            name: 'px : 579 x 413',
            color: 'cyan',
            icon: 'mm : 49 x 35',
            px:'579,413',
          },
          
        ],
      },
    ],
    elements: [{
        title: '一寸',
        name: 'px : 295 x 413',
        color: 'purple',
        icon: 'mm : 25 x 35'
      },
      {
        title: '二寸 ',
        name: 'px : 413 x 579',
        color: 'mauve',
        icon: 'mm : 35 x 49'
      },
      {
        title: '列表',
        name: 'list',
        color: 'pink',
        icon: 'list'
      },
      {
        title: '卡片',
        name: 'card',
        color: 'brown',
        icon: 'newsfill'
      },
      {
        title: '表单',
        name: 'form',
        color: 'red',
        icon: 'formfill'
      },
      {
        title: '时间轴',
        name: 'timeline',
        color: 'orange',
        icon: 'timefill'
      },
      {
        title: '聊天',
        name: 'chat',
        color: 'green',
        icon: 'messagefill'
      },
      {
        title: '轮播',
        name: 'swiper',
        color: 'olive',
        icon: 'album'
      },
      {
        title: '模态框',
        name: 'modal',
        color: 'grey',
        icon: 'squarecheckfill'
      },
      {
        title: '步骤条',
        name: 'steps',
        color: 'cyan',
        icon: 'roundcheckfill'
      },
    ],
  },
  //事件处理函数
  tabSelect(e) {
    var _this=this;
    this.setData({
      TabCur: e.currentTarget.dataset.id,
      scrollLeft: (e.currentTarget.dataset.id - 1) * 60,
      elements:_this.data.navList[e.currentTarget.dataset.id].elements,
    })
  },
  onLoad: function () {
    var _this=this;
    console.log(_this.data.TabCur);
    this.setData({
      elements:_this.data.navList[_this.data.TabCur].elements,
    })
  },

})